project_name: qron
archives:
  - id: qron-dev
    files:
      - LICENSE.md
    format: tar.gz
    name_template: "{{.Binary}}_{{.Version}}_{{.Os}}-{{.Arch}}"
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/httpdev
    id: qron-dev
    binary: qron-dev
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
