services:
  postgres:
#    image: supabase/postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
      # Can be set at session level
      # - TZ=UTC
      # - PGTZ=UTC
    ports:
      - 5435:5432
  pyroscope:
    image: 'pyroscope/pyroscope:latest'
    ports:
      - '4040:4040'
    command:
      - 'server'
