// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateJobArgs struct {
	RunAt  string `json:"run_at"`
	Name   string `json:"name"`
	State  string `json:"state"`
	URL    string `json:"url"`
	Method string `json:"method"`
}

type QueryJobsArgs struct {
	Limit  int    `json:"limit"`
	Skip   int    `json:"skip"`
	Filter string `json:"filter"`
}

type UpdateJobArgs struct {
	RunAt  *string `json:"run_at"`
	State  *string `json:"state"`
	URL    *string `json:"url"`
	Method *string `json:"method"`
}
