// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// Job defines model for Job.
type Job struct {
	// Unique id of the job
	Id int64 `json:"id"`

	// When to run the job
	RunAt string `json:"run_at"`
}

// NewJob defines model for NewJob.
type NewJob struct {
	// When to run the job
	RunAt string `json:"run_at"`
}

// ScheduleJobJSONBody defines parameters for ScheduleJob.
type ScheduleJobJSONBody = NewJob

// ScheduleJobJSONRequestBody defines body for ScheduleJob for application/json ContentType.
type ScheduleJobJSONRequestBody = ScheduleJobJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Schedule job
	// (POST /schedule)
	ScheduleJob(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ScheduleJob converts echo context to params.
func (w *ServerInterfaceWrapper) ScheduleJob(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ScheduleJob(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/schedule", wrapper.ScheduleJob)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xTz47TPBB/FWu+7xhtuu2Kg49IHOgBhABxWFXIjSeNV4nHOx4vVFXeHdlJl9J2EYc9",
	"1fWMf/9mcoCGhkAevUTQB4hNh4Mpx3fMxPkQmAKyOCzXDVnMvxZjwy6IIw96alalVkFLPBgBDc7LagkV",
	"yD7g9Bd3yDBWMGCMZvci0LH8/DQKO7+DcayA8TE5Rgv6HmbCY/tmrGBN24xq+v5jC/r+AP8ztqDhv/q3",
	"03q2WX/AH7l/rM5dOnsp7at3jwmVs4paJR2qB9qeuX1zd8XtmWZnYTNmpTP5RcKc/PcMeM7/rUOvhBQn",
	"f0L/94BmrM2YC863dAn7xfn9JxWRn5AznpMej9dQwRNynBpvbxY3izw8CuhNcKBhVa4qCEa6or0ka1Nf",
	"JhsoXrHxee6Y9WfnJpfe25PiutSyE4zylux+Wj0v6AukCaF3TXlXP8SMe9zdfPqXkedA/hS2pq0Khs2A",
	"ghzhNEjhhCXZGMjHaUzLxeLVRL2g6DmqIzGUltakXl6Ne/rOr7Anjz8DNoJW4dxTQUzDYHh/PsfyfNqh",
	"WL66xD1o6ESCruueGtN3FEXfLld3dd6dcTP+CgAA//8RrimifAQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
