// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Error defines model for Error.
type Error struct {
	// Error code
	Code int32 `json:"code"`

	// Error message
	Message string `json:"message"`
}

// Job defines model for Job.
type Job struct {
	// Unique id of the job
	Id int64 `json:"id"`

	// When to run the job
	RunAt string `json:"run_at"`
}

// NewJob defines model for NewJob.
type NewJob struct {
	// When to run the job
	RunAt string `json:"run_at"`
}

// ScheduleJobJSONBody defines parameters for ScheduleJob.
type ScheduleJobJSONBody = NewJob

// ScheduleJobJSONRequestBody defines body for ScheduleJob for application/json ContentType.
type ScheduleJobJSONRequestBody = ScheduleJobJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Schedule job
	// (POST /schedule/{id})
	ScheduleJob(ctx echo.Context, id int) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ScheduleJob converts echo context to params.
func (w *ServerInterfaceWrapper) ScheduleJob(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithLocation("simple", false, "id", runtime.ParamLocationPath, ctx.Param("id"), &id)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ScheduleJob(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/schedule/:id", wrapper.ScheduleJob)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUwW7bOhD8FWLfOxKRYwc98Fi0h/iQomiLHgKjoMWVxUAimSWZ1jD47wUpKVVkp+gh",
	"J8vc0ewMZ6AT1LZ31qAJHsQJfN1iL8vjRyJL+cGRdUhBYzmurcL8q9DXpF3Q1oAYwKzMODSWehlAgDZh",
	"swYO4ehw+IsHJEgcevReHl4lmsbPr/pA2hwgJQ6Ej1ETKhD3MC6c4LvEYWv3mVV23acGxP0J/idsQMB/",
	"1R+n1WizusOfGZ/40qVW59K+Gf0YkWnFbMNCi+zB7hdu391ccLvQrBXsUlY6Lj+7YYrmRyZc7v/eomHB",
	"Mopmtv7vFzRy7VIeaNPYc9qv2hw/M4/0hJT5dOhwOgYOT0h+AF5fra5WOTzr0EinQcCmHHFwMrRFe7lZ",
	"FTusTlql4s36C16+jLDRRLYv8+hWzYbbMnOSZI8ByZc4X/LcxR5J1+z2wxTKJACyXxBFGnAwsi+hKJhf",
	"UKCIfCx9FnkW3W5Aow/vrToO/TcBTbEknet0XXRXDz7rOc24/qV3OZWXhrZ2z2aOl2JLvN5Z44eurFer",
	"NxP1iqLnqKbFUCCNjF14s93Dx+bC9mjwl8M6oGI4Yjj42PeSjsseldeHIg9didSBgDYEJ6qqs7XsWuuD",
	"uF5vbqpc4LRLvwMAAP//zeRf0QEFAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
